### ISSUE TITLE
Оффер по внешнему виду Галерея на главной

### ISSUE THREAD

**Issue by nikolaymsp** [nikolaymsp/shield-fond#11]
Предложение по внешнему виду галереи, в которой будут общие снимки, или рендеры от 3 до 5 шт.
![галерея](https://user-images.githubusercontent.com/62141807/106631538-ea433800-658d-11eb-87c8-d7074c556ac9.jpg)

спизжено с http://onegin.land

**Comment by WizardusAnemia** [comment]
Воткнул. Надо будет с размером картинок разобраться. Туда поменьше запихивать.
