### ISSUE TITLE
Раздел "Сколько стоит?"

### ISSUE THREAD

**Issue by nikolaymsp** [nikolaymsp/shield-fond#14]
Предлагаю назвать данный раздел "Условия покупки"

Заполнить согласно скриншота

Высоту блоков увеличить, чтобы внешне было похоже на макет
![image](https://user-images.githubusercontent.com/62141807/106763804-41a5de80-6648-11eb-8904-ac6f2553c428.png)

**Comment by WizardusAnemia** [comment]
По дезигну посмотри. А так, там еще через media-запросы в css править и править под экраны
