### ISSUE TITLE
Замена логотипа

### ISSUE THREAD

**Issue by nikolaymsp** [nikolaymsp/shield-fond#25]
по возможности заменить лого на свг. для хедера мальца поменял стиль,
Желательно чтобы на мобиле лого влезало в одну строку с меню и лупой, так как если оно сильно больше по высоте блока то он растягивается и страница смотрится не красиво.
![logo-footer](https://user-images.githubusercontent.com/62141807/120648917-d8629a80-c484-11eb-921b-862cd31180be.png)
![logo-header](https://user-images.githubusercontent.com/62141807/120648919-d8fb3100-c484-11eb-9a16-a327e783252c.png)

Ссылка на свг аи и пнг файлы: https://drive.google.com/drive/folders/1E33QvwD0TZwd3Q0_aJEvfInTQzgmLSya?usp=sharing

**Comment by WizardusAnemia** [comment]
Глянь мобилу, дописал чуть цсс, может сойдет
