### ISSUE TITLE
На главной вывести ссылки на социальные сети

### ISSUE THREAD

**Issue by nikolaymsp** [nikolaymsp/shield-fond#44]
#43 

из соцсетей только инстаграм.

**Comment by nikolaymsp** [comment]
А чего убрал из блока "о нас" на главной?
+ в футере как то смещено странно к центу, не так как у шабла в стоке.

**Comment by WizardusAnemia** [comment]
> А чего убрал из блока "о нас" на главной?
> 
> * в футере как то смещено странно к центу, не так как у шабла в стоке.

О нас - вернул, футер - выровнял
