### ISSUE TITLE
Номер телефона выведен, но выравнивание у него не корректное

### ISSUE THREAD

**Issue by nikolaymsp** [nikolaymsp/shield-fond#61]
Десктоп версия

как есть: 
![image](https://user-images.githubusercontent.com/62141807/145703787-98558405-56c7-4752-b260-ee3287e6d4bd.png)
как надо:
![Без-имени-1](https://user-images.githubusercontent.com/62141807/145703829-d09ee4d5-1bd8-4158-a9ec-fb13132d20b0.jpg)

**Comment by WizardusAnemia** [comment]
Туда не влезет, здесь только последним элементом меню
