### ISSUE TITLE
Номер телефона выведен, но выравнивание у него не корректное

### ISSUE THREAD

**Issue by nikolaymsp** [nikolaymsp/shield-fond#62]
Мобильная версия и около планшетные варианты:
![image](https://user-images.githubusercontent.com/62141807/145703872-054b72f0-11dd-4dec-8a74-7425f35d4b67.png)
![image](https://user-images.githubusercontent.com/62141807/145703875-1e88d3e2-3654-4012-850e-810531fd2881.png)
Есть смысл ввести выравнивание по левой стороне как и у текста: 
![image](https://user-images.githubusercontent.com/62141807/145703890-04147924-1a1b-44f7-8eb0-1bb57a9d52bd.png)

**Comment by WizardusAnemia** [comment]
Смысл есть. Меня еще эта иконка бесит, может убрать ее нахер?
