### ISSUE TITLE
Добавить кнопку "Перейти" в разделе Генплан

### ISSUE THREAD

**Issue by nikolaymsp** [nikolaymsp/shield-fond#7]
Создать кнопку в разделе генплан на главной исходя из референса

Бекграунд полная ширина блока, прозрачность 20%

Attachments : https://drive.google.com/file/d/1y9IF1OH3BhdPoi6K71RPTqGOU8zBPr14/view?usp=sharing

**Comment by WizardusAnemia** [comment]
Файл перенесен в корзину, пишет.

**Comment by nikolaymsp** [comment]
> Файл перенесен в корзину, пишет.

https://drive.google.com/drive/folders/1P0_NpMQAmXPnUmneiiPOe1YwisZl6i5K
